name: "GitBot Config: Automated Git User Setup for GitHub Actions"
description: "Streamline your GitHub Actions workflows with GitBot Config. This action automatically configures the Git user as the GitHub Actions bot, ensuring proper commit attribution with zero manual setup. Perfect for CI/CD pipelines, automated releases, and any workflow requiring Git operations."
branding:
  icon: 'git-branch'
  color: 'blue'
runs:
  using: "composite"
  steps:
    - run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
      shell: bash
