name: "Config Git Actions Bot"
description: "Sets up Git global configuration to use GitHub Actions bot as the committer. This action configures the Git user.email and user.name globally, attributing commits in workflows to the GitHub Actions bot."
branding:
  icon: "git-branch"
  color: "blue"
runs:
  using: "composite"
  steps:
    - run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
      shell: bash
