name: "Config Git and Attest Build Provenance"
description: "Configures Git globally to use GitHub Actions bot as committer and attests build provenance"
branding:
  icon: "git-branch"
  color: "blue"

inputs:
  subject-path:
    description: 'Path to the artifact to attest'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure Git
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
      shell: bash

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1.4.1
      with:
        subject-path: ${{ inputs.subject-path }}
