name: "GitBot Config: Automated Git User Setup for GitHub Actions"
description: "Automatically configure Git user as GitHub Actions bot. Ensures proper commit attribution in workflows with zero setup."
branding:
  icon: 'git-branch'
  color: 'blue'
runs:
  using: "composite"
  steps:
    - run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
      shell: bash
