name: Generate and Verify Attestation
on: [push, pull_request]

jobs:
  attestation:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
      packages: read
      attestations: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Calculate SHA256
      id: sha256
      run: |
        REPO_ROOT=$(git rev-parse --show-toplevel)
        HASH=$(find "$REPO_ROOT" -type f -not -path '*/\.git/*' -print0 | sort -z | xargs -0 sha256sum | sha256sum | awk '{print $1}')
        echo "digest=sha256:$HASH" >> $GITHUB_OUTPUT

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ github.repository }}
        subject-digest: ${{ steps.sha256.outputs.digest }}

    - name: Find attestation file
      id: find_attestation
      run: |
        ATTESTATION_FILE=$(find . -name "*.intoto.jsonl" -type f)
        if [ -z "$ATTESTATION_FILE" ]; then
          echo "Error: Attestation file not found"
          exit 1
        fi
        echo "file=$ATTESTATION_FILE" >> $GITHUB_OUTPUT

    - name: Upload attestation
      uses: actions/upload-artifact@v3
      with:
        name: attestation
        path: ${{ steps.find_attestation.outputs.file }}
        if-no-files-found: error
